<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
		<string>htm</string>
		<string>xhtml</string>
		<string>tumblr</string>
		<string>theme</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\{block:([a-zA-Z0-9_:])+\b.*?\})|(&lt;(head|table|tr|div|style|script|ul|ol|form|dl)\b.*?&gt;)</string>
	<key>foldingStopMarker</key>
	<string>(\{/block:([a-zA-Z0-9_:])+\})|(&lt;/(head|table|tr|div|style|script|ul|ol|form|dl)&gt;)</string>
	<key>keyEquivalent</key>
	<string>^~E</string>
	<key>name</key>
	<string>Tumblr</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#tumblr-tag</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(DOCTYPE)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.doctype.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&gt;)</string>
			<key>name</key>
			<string>meta.tag.sgml.doctype.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>"[^"&gt;]*"</string>
					<key>name</key>
					<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>This is set to use XHTML standards, but you can change that by changing .strict to .basic for HTML standards</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>css</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:style))\b(?![^&gt;]*/&gt;)[^.&gt;]*&gt;?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/((?i:style))&gt;(?:\s*\n)?</string>
			<key>name</key>
			<string>source.css.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>embedded-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#css</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&amp;([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+);</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>javascript</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:script))\b(?![^&gt;]*/&gt;)[^&gt;]*&gt;?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/((?i:script))&gt;(?:\s*)?</string>
			<key>name</key>
			<string>source.js.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z0-9-_:]+)</string>
			<key>name</key>
			<string>constant.name.tag.ee</string>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>tumblr-tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{/?([a-zA-Z0-9_:]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.name.tag.tumblr</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>tumblr.tag.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.tumblr</string>
	<key>uuid</key>
	<string>DC474EDA-419E-4B59-B7E6-9C537B18B9EF</string>
</dict>
</plist>
